#!/bin/bash

FILES=(
	"../../Plugins/**/*.js"
)
TRANSFORMS=(
	./test_transforms/objectify.js 
	./test_transforms/tabTo2Spaces.js
	./test_transforms/trimSpacesBeforeNewLine.js
)
AFTER_ALL=(
	./test_transforms/applyChanges.js
)
(cd node_modules/reshape/; ./reshape -p ${FILES[@]} -e ${TRANSFORMS[@]} -aa ${AFTER_ALL[@]})
